{
 "title": "first",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "OS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\"}[1m])))",
     "legendFormat": "CPU 사용률(%)"
    },
    {
     "expr": "100 * (windows_memory_committed_bytes / windows_memory_commit_limit)",
     "legendFormat": "Commit 사용률(%)"
    },
    {
     "expr": "100 * (1 - (windows_memory_available_bytes / windows_memory_physical_total_bytes))",
     "legendFormat": "Physical 사용률(%)"
    }
   ]
  },
  {
   "title": "톰켓 스레드",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(tomcat_threads_current_threads)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(tomcat_threads_busy_threads)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(tomcat_threads_config_max_threads)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "평균지연시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum[1m])\r\n/\r\nrate(http_server_requests_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "톰캣 커넥션",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(tomcat_connections_current_connections)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(tomcat_connections_keepalive_current_connections)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(tomcat_connections_config_max_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, uri)(rate(http_server_requests_seconds_bucket[1m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, uri)(rate(http_server_requests_seconds_bucket[1m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error(500)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m])) /\r\nsum(rate(http_server_requests_seconds_count[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}