{
 "title": "부하-테스트",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "메모리",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - (windows_memory_available_bytes / windows_memory_physical_total_bytes))",
     "legendFormat": "사용률(physical %)"
    }
   ]
  },
  {
   "title": "DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "hikaricp_connections_active", "legendFormat": "active" },
    { "expr": "hikaricp_connections", "legendFormat": "active + idle" }
   ]
  }
 ]
}